import { Controller, Get, NotFoundException, Param, Query } from '@nestjs/common';
import { DiscoveryService } from '../application/discovery.service';
import { PickupSlotService } from '../application/pickup-slots.service';
import { DiscoveryQueryDto } from './dto/discovery.dto';
import { MerchantDetailView, MerchantSummaryView, PickupSlotsView } from './merchant.views';

const DEFAULT_LIMIT = 20;

/**
 * Public storefront.
 *
 * Unauthenticated on purpose: browsing the catalogue must not require an
 * account, or the funnel starts with a signup wall. Only `ACTIVE` merchants are
 * ever returned — `DiscoveryService` enforces that in the query, not here.
 *
 * Note the plural `merchants` for the public catalogue versus the singular
 * `merchant/:merchantId/...` used by the owner and admin portals. The prefix
 * tells you which authorisation model applies.
 */
@Controller('merchants')
export class DiscoveryController {
  constructor(
    private readonly discovery: DiscoveryService,
    private readonly pickupSlots: PickupSlotService,
  ) {}

  /**
   * Ranked discovery.
   *
   * Returns a top-N rather than a page: with an origin the results are ordered
   * by a scoring policy, and "page 3 of best" is not a meaningful request.
   * `hasMore` tells the client whether to invite a narrower search instead.
   *
   * `sort` picks the policy (`NEAREST` by default — pure distance, which is
   * what this endpoint did before ranking existed). The scoring rules live in
   * `MerchantRankingEngine` in the domain package, not here.
   */
  @Get()
  async list(
    @Query() query: DiscoveryQueryDto,
  ): Promise<{ data: MerchantSummaryView[]; hasMore: boolean }> {
    const limit = query.limit ?? DEFAULT_LIMIT;
    const data = await this.discovery.list({
      latitude: query.latitude,
      longitude: query.longitude,
      radiusKm: query.radiusKm,
      q: query.q,
      district: query.district,
      acceptingOnly: query.acceptingOnly,
      sort: query.sort,
      limit,
    });

    return { data, hasMore: data.length >= limit };
  }

  /** Districts that currently have at least one active merchant. */
  @Get('districts')
  districts(): Promise<{ district: string; count: number }[]> {
    return this.discovery.districts();
  }

  @Get(':slug')
  async detail(@Param('slug') slug: string): Promise<MerchantDetailView> {
    const merchant = await this.discovery.detail(slug);
    if (!merchant) throw new NotFoundException('Merchant not found');
    return merchant;
  }

  /**
   * The times this merchant can actually be collected from.
   *
   * Served by the API so the browser never has to re-implement opening hours
   * and lead time; the slots it returns are generated by the same policy
   * `POST /orders` validates against.
   */
  @Get(':slug/pickup-slots')
  async slots(@Param('slug') slug: string): Promise<PickupSlotsView> {
    const view = await this.pickupSlots.forSlug(slug);
    if (!view) throw new NotFoundException('Merchant not found');
    return view;
  }
}
